detect_cans_in_fridge_201202/launch/perception.launch
detect_cans_in_fridge_201202/launch/startup.launch

* デモが動かなくなるバグを以前入れてしまっていたので、その修正（通常のデモでは画像処理をかける領域の切り抜きを行わない形に変更）
jsk_perception下のkalmanfiltered-object-detection-marker.lと、attention-clipperに関するnodeがセットとなって画像の切り抜きが機能する形をとっているので、kalmanfiltered-object-detection-marker.lを立ち上げないデモのlaunchファイルではデモが止まってしまうようになっていた。通常のデモでは切り抜きを行わずそのまま処理する形にした。

fix perception.launch

---

jsk_2015_06_hrp_drc/drc_task_common/catkin.cmake
jsk_2015_06_hrp_drc/drc_task_common/euslisp/request-ik-from-marker.l
jsk_2015_06_hrp_drc/drc_task_common/msg/TMarkerInfo.msg
jsk_2015_06_hrp_drc/drc_task_common/scripts/b_control_client.py
jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/manipulation_data_server.cpp

manipulation_data_serverのプログラム周りを変更しました．
* エラーと，不必要なコードを消しました
* 後で拡張しやすいように，ひとまとまりのプログラムを関数化しました
* デバッグ用で明らかに不必要と思われるros_infoを消しました
* 指定した:軸周りに:ｘでIKを解く時の，選択肢を２つにしました．手元のインタラクティブマーカーにIKの結果をFEEDBACKするかどうかです．

Clean codes around manipulation server

---

jsk_2015_06_hrp_drc/drc_com_common/package.xml

https://github.com/jsk-ros-pkg/jsk_demos/commit/ea19aea260bfb02fa370094bf2781eeb4eb68a70#commitcomment-9434538

Fix typo in drc_com_common : rosbuid -> rosbuild

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l

`timered-state-machine` is a state machine with timelimit.
If timelimit is specified, state will be automatically changed to next state.
It's useful to implement "timeout".
```lisp
(load "state-machine.l")
;; make state machine
(setq white-rabbit-state (make-state-machine
'((:initial -> :tea-party)
(:tea-party -> :duchess)
(:duchess -> :heart-trial)
(:heart-trial -> :initial))
'((:initial :alice-in-wonderland)
(:tea-party :alice-in-wonderland)
(:duchess :alice-in-wonderland)
(:heart-trial :alice-in-wonderland))
:initial nil))
;; register timeout
(send (send white-rabbit-state :node :initial)
:add-timelimit 10 :tea-party)
(send (send white-rabbit-state :node :tea-party)
:add-timelimit 10 :duchess)
(send (send white-rabbit-state :node :duchess)
:add-timelimit 10 :heart-trial)
(send (send …
```

[drc_task_common] Add timered-state-machine class to add timelimit to state machine

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l

Now it really does look like smach subgraph.

[drc_task_common] Visualize state which has same context (same subgraph)

---

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt

I don't know the best way...
* Download pcd files from www.jsk.t.u-tokyo.ac.jp in compiling
* I didn't use jsk-ros-pkg/archives because it would be heavy task to download large file ...??

[drc_task_common] Download pcd models in compiling

---

jsk_2015_06_hrp_drc/drc_task_common/scripts/drill_button_publisher.py

use tf that TransformableMarker publishes.
show button position as marker(topic name /button_marker)

add drill button marker publisher

---

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt

drill のモデルをmake時にdownload するスクリプトを加えました。
写真は、.daeをインタラクティブマーカーにして、実世界の点群と合わせてます。

add gun_drill downloader

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l

Define terrain link as bodyset-link.
@mmurooka 
cascaded-link's `links` should be made of `bodyset-link` class.

Define terrain link as bodyset-link

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l
jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l
jsk_2015_06_hrp_drc/drc_task_common/euslisp/request-ik-from-marker.l
jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-util.l

[メモ]
RvizのGUIから関節角を送るときに，wait-interpolationできるようにする．
このPRは send-angle-vector-from-ocs をせずに，wait-interpolation-from-ocs をすると，返ってこなくなる仕様．
なおすには，OCS側でangle-vectorを送る状態を追加して，その状態を監視すればよい．

[drc_task_common] add function to wait interpolation in ocs

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/robot-driving-controller.l
jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/handle_operation_interface.launch
jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/DriveCmdInterrupter.py

Modify namespace for operation cmd topic: staro_drive -> drive

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-door-task.l

・door-paramの:initで，hindgeジョイントの正負の向きを，ヒンジが左右のどちらかにあるかによって反転させるようにする
・左手時のreach, releaseの経由点を少しかえる
・test-door-open-drc-sagami-door で動作ができるようにする

[drc_task_common] extend door program for sagami environment

---

jsk_2015_06_hrp_drc/drc_task_common/package.xml

Be careful: You need to install ar_tools into your ros workspace by
```
$ wstool set --git ar_tools https://github.com/ar-tools/ar_tools.git
```

[drc_task_common] Add script to convert ar_pose/ARMarker to geometry_msgs/PoseStamped

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l

use :active-state method instead of slot 'active-state' directly in `state-machine.l`

[drc_task_common] use :active-state method instead of slot 'active-state'

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l

タイポを直しました。
トンネルありの環境で、 start-grasp, stop-grasp, start-impedance, stop-impedance が動くことを確認しました。

fix typo start-grasp command

---

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt

parenteses is needed without knowing why
```
leus@leus-ThinkPad-W541:~/ros/hydro/src/jsk-ros-pkg/jsk_demos/jsk_2015_c/drc_task_common$ ls models
ls: cannot access models: No such file or directory
leus@leus-ThinkPad-W541:~/ros/hydro/src/jsk-ros-pkg/jsk_demos/jsk_2015_06_hrp_drc/drc_task_common$ git checkout master
Already on 'master'
leus@leus-ThinkPad-W541:~/ros/hydro/src/jsk-ros-pkg/jsk_demos/jsk_2015_06_hrp_drc/drc_task_common$ catkin bt > hoge.txt
leus@leus-ThinkPad-W541:~/ros/hydro/src/jsk-ros-pkg/jsk_demos/jsk_2015_06_hrp_drc/drc_task_common$ ls models
ls: cannot access models: No such file or directory
leus@leus-ThinkPad-W541:~/ros/hydro/src/jsk-ros-pkg/jsk_demos/jsk_2015_06_hrp_drc/drc_task_common$ git checkout add_parentheses 
Switched to branch 'add_parentheses' …
```

add_parentheses

---

jsk_2013_04_pr2_610/euslisp/move-chair.l
jsk_2013_04_pr2_610/euslisp/pick-broom.l
jsk_2013_04_pr2_610/euslisp/pick-cloth.l
jsk_2013_04_pr2_610/euslisp/pick-tray.l
jsk_2013_04_pr2_610/euslisp/put-cloth-into-laundry.l
jsk_demo_common/euslisp/pr2-action.l

Instead of recognizing the positions of fridge handle or can, the positions are given.
So, the behavior of PR2 is shortly different.
(For example, think about PR2 approach to the fridge handle.
In real, PR2 approach to the fridge several times because the distance between PR2 and fridge handle is not in the given thereshold.
But, in irtviewer, PR2 approach to the fridge only one time because I just give the handle position and PR2 just grasp that position.)
It might be better to be able to execute demo in kinematics mode too.
(Because in kinematics mode, go-pos is simulated, and these situations can be simulated. )

exec in simulation mode

---

jsk_demo_common/euslisp/pr2-action.l

fix for change of calling link name directly in pr2-interface

[jsk_demo_common/euslisp/pr2-action.l] fix: add '_lk' to link name

---

jsk_2015_06_hrp_drc/gazebo_drive_simulator/CMakeLists.txt

this blocks https://travis-ci.org/jsk-ros-pkg/jsk_smart_apps/jobs/74776198 (https://github.com/jsk-ros-pkg/jsk_smart_apps/pull/56) with
```
]2;[build] 3/21[[36mgazebo_drive_simulator[0m] +/usr/bin/env PYTHONPATH=/home/travis/ros/ws_jsk_smart_apps/install/lib/python2.7/dist-packages:/home/travis/ros/ws_jsk_smart_apps/build/gazebo_drive_simulator/lib/python2.7/dist-packages:/opt/ros/hydro/lib/python2.7/dist-packages CATKIN_BINARY_DIR=/home/travis/ros/ws_jsk_smart_apps/build/gazebo_drive_simulator /usr/bin/python /home/travis/ros/ws_jsk_smart_apps/src/jsk-ros-pkg/jsk_demos/jsk_2015_06_hrp_drc/gazebo_drive_simulator/setup.py build --build-base /home/travis/ros/ws_jsk_smart_apps/build/gazebo_drive_simulator install --install-layout=deb --prefix=/home/travis/ros/ws_jsk_smart_apps/install …
```

gazebo_drive_simulator does not have python modules

---

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-door-task.l

euslib以下のプログラムのloadをなくしてもtest-door-motion.lのtest-door-finalが動いたのを確認しました

remove program because not used

---

jsk_2015_06_hrp_drc/drc_task_common/launch/transformable_model.launch

インタラクティブマーカーの操作の仕方がodom相対でfixedになっていたので戻しています．

change rviz interactive marker coordinates

---

detect_cans_in_fridge_201202/euslisp/async-join-based-parallel-smach-main.l
detect_cans_in_fridge_201202/euslisp/base-go-to-fridge-init-pose.l
detect_cans_in_fridge_201202/euslisp/base-go-to-fridge.l
detect_cans_in_fridge_201202/euslisp/close-fridge.l
detect_cans_in_fridge_201202/euslisp/detach-fridge-handle.l
detect_cans_in_fridge_201202/euslisp/go-back-from-fridge.l
detect_cans_in_fridge_201202/euslisp/grasp-can-init.l
detect_cans_in_fridge_201202/euslisp/grasp-can-motion.l
detect_cans_in_fridge_201202/euslisp/grasp-can-posing.l
detect_cans_in_fridge_201202/euslisp/look-at-fridge.l
detect_cans_in_fridge_201202/euslisp/move-forward-larm.l
detect_cans_in_fridge_201202/euslisp/move-to-and-open-fridge-door.l
detect_cans_in_fridge_201202/euslisp/move-to-can-spot.l
detect_cans_in_fridge_201202/euslisp/open-fridge-door-initial-pose.l
detect_cans_in_fridge_201202/euslisp/swipe-fridge-door.l
detect_cans_in_fridge_201202/launch/fridge_demo.launch
jsk_demo_common/euslisp/pr2-action.l

* When you want to execute an action, async-join-based-structure-hazard-check-state-machine manages this action by managing 3 states (check, join, and exec state).
* checks whether or not executing action is possible by considering structure hazard. If possible, transitions to exec state. If not possible, transitions to join state
* wait until the actions ends
* execute the action.

[detect_cans] async join based parallel state-machine

---

jsk_demo_common/euslisp/pr2-action.l

move-to-and-open-fridgeの冷蔵庫のドアにてを近づけるドウサの前の姿勢で、reset-poseではなく肘がかなり内側に入った姿勢だと、その後のドアをあける動作列で手先の向きが正しくなくなってしまいます。
本質的な解法はhttps://github.com/jsk-ros-pkg/jsk_demos/blob/0.0.2/jsk_demo_common/euslisp/pr2-action.l#L390 でrotation-axis :z ではなくて、+-60度とかの指定を出きるようにすることかと思いました。

pr2-action.l: apply reset-pose before open-fridge-func

---

detect_cans_in_fridge_201202/euslisp/main.l

Applying this PR, `(enable-behavior-server)` is called only once after end of every demos
This fixes https://github.com/jsk-ros-pkg/jsk_demos/issues/1057

[detect_cans_in_fridge_201202/euslisp/main.l] bugfix: prevent calling (enable-behavior-server) many times

---

detect_cans_in_fridge_201202/euslisp/match-hist.l

sometimes stucks on retrying detect cans

[detect_cans_in_fridge_201202/euslisp/match-hist.l] update parameter for match hist lower cutting threshold

---

detect_cans_in_fridge_201202/CMakeLists.txt

this is necessary for generating manifest.l

[detect_cans_in_fridge_201202/CMakeLists.txt] add roseus to find_package

---

elevator_move_base_pr2/src/push-elevator-button.l

[elevator_move_base_pr2/src/push-elevator-button.l] use require instead of load pr2-interface

---

detect_cans_in_fridge_201202/launch/gazebo_startup.launch
detect_cans_in_fridge_201202/launch/perception.launch
detect_cans_in_fridge_201202/launch/startup.launch

current launch files does not work without this fix.

[detect_cans_in_fridge_201202] fix: wrong arg name at some launch files

---

.travis.yml
.travis_before_script_hydro.bash
detect_cans_in_fridge_201202/euslisp/detect_cans.l
detect_cans_in_fridge_201202/package.xml
jsk_2011_07_pr2_semantic/euslisp/actions.l
jsk_2011_07_pr2_semantic/package.xml
jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/manipulation_data_server.cpp

Some packages in jsk_visualization depends on jsk_pcl_ros because it uses the srv files.
But jsk_pcl_ros is a very large package and the dependency should be avoided ideally.
The solution is placing `msg/srv` files into `jsk_recognition_msgs`.
1. Merge this after `jsk_recognition_msgs` is released: http://repositories.ros.org/status_page/ros_indigo_default.html?q=jsk_recognition_msgs
1. Release this pacakge.
1. Remove `jsk_pcl_ros/srv`.
1. Release `jsk_pcl_ros`.
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1914

Migrate srv files from jsk_pcl_ros to jsk_recognition_msgs

---

jsk_demo_common/euslisp/pr2-action.l
jsk_demo_common/euslisp/pr2-attention-action.l

- `generate-slide-path`, `generate-circle-path`: docstring should after function definition
- add missing `move-arm` function
Special thanks to @asilx !
BTW, why demos have worked well without this fix...?

[jsk_demo_common] some bugfix

---

jsk_maps/src/eng2-scene.l

This is updated version of https://github.com/jsk-ros-pkg/jsk_demos/pull/1232.
Recently, position of fetch's dock was changed.

Add fetch's dock spot to /spots_marker_array

---

.travis.yml
jsk_2013_04_pr2_610/CMakeLists.txt
jsk_2013_04_pr2_610/package.xml

- set kinetic as allow failure
- add run_depend smach_viewr to jsk_2013_04_pr2_610
```
[/workspace/ros/ws_jsk_demos/src/jsk_demos/jsk_2013_04_pr2_610/launch/planner.launch]:
Missing package dependencies: task_compiler/package.xml: smach_viewer
cannot find package [smach_viewer] for node [smach_viewer.py] unable to
find node [smach_viewer/smach_viewer.py]: smach_viewer ROS path
[0]=/opt/ros/kinetic/share/ros
```
https://github.com/tork-a/jsk_planning-release/blob/release/kinetic/task_compiler/package.xml#L25
- add melodic test and remove indigo/kinetic from allow_failures
- remove unnecessary packages from find_package, remaining package lists are used in generate_mesages
- update jsk_travis to 0.5.0
- set kinetic as a allow failure
need to wait for …

udpate to jsk_travis 0.5.0

---

jsk_maps/tools/initialpose3d.py

use `rospy.logerr` instead of `print` in `initialpose3d.py`

[jsk_maps] use rospy.logerr in initialpose3d

---

elevator_move_base_pr2/src/color_point_detector.cpp

this PR fixs opencv include header file path.
`opencv/cv.h` is removed in `opencv4`.
use `cv::Scalar` instead of `CV_RGB`

[elevator_move_base_pr2] fix opencv for opencv4

---

rwt_teleop/apps/rwt_teleop/rwt_teleop.app

sorry, but there is a commit which is not included in #1337 .
this PR fix typo in `rwt_teleop`.
This PR is now running in PR1040.

[rwt_teleop] fix typo in rwt_teleop.app

---

jsk_2013_04_pr2_610/README.md

I was trying to do the installation and got the following error output.
```
$ wstool merge https://raw.githubusercontent.com/jsk-ros-pkg/jsk_demos/master/jsk_2013_04_pr2_610/jsk_2013_04_pr2_610.rosinstall
ERROR in config: Command requires a target workspace.
```
This PR avoids this error by adding the `-t src` option.
The `-t src` option is also used for Github Action CI.
https://github.com/jsk-ros-pkg/jsk_demos/blob/74a2c31203af453150a1ea9d159ff5b76dd35179/.travis.before_script.sh#L12
FYI: The following is a ROS Answer that solves a similar problem.
https://answers.ros.org/question/191130/error-in-catkin_ws/

[jsk_2013_04_pr2_610] Fix installation README

---

jsk_maps/launch/map_eng2.rviz
jsk_maps/launch/start_map_eng2.launch
jsk_maps/tools/publish_scene.l

Add node to publish building model as a Marker
1) start launch file
```
roslaunch jsk_maps start_map_eng2.launch use_machine:=true
```
2) start publish_scene.l node
```
rosrun jsk_maps publish_scene.l
```
3) start rviz
```
rviz -d $(rospack find jsk_maps)/launch/map_eng2.rviz
```
If we merge https://github.com/jsk-ros-pkg/jsk_roseus/pull/713, we can cleanup `publish_scene.l` node
Question :
Do we use `start_map_eng2.launch` in pr2/fetch startup? if so , can we add `publish_scene.l` to `start_map_eng2.launch`?
Cc: @tkmtnt7000

jsk_maps: add publish_scene.l

---

rwt_teleop/www/index.html

this PR fix `jquery` path for `rwt_teleop`.
`jquery` path is modified in https://github.com/tork-a/visualization_rwt/pull/124
cc. @sktometometo

[rwt_teleop] fix jquery path for rwt_teleop

---

welcome_to_jsk_fetch/CMakeLists.txt

pr1040 build failure in `welcome_to_jsk_fetch`.
```
______________________________________________________________________________________________________________
Errors << welcome_to_jsk_fetch:cmake /home/applications/ros/indigo/logs/welcome_to_jsk_fetch/build.cmake.001.log
-- set EUSDIR to /home/applications/ros/indigo/devel/share/euslisp/jskeus/eus
-- set ARCHDIR to Linux64
CMake Error at /home/applications/ros/indigo/devel/share/jsk_robot_startup/cmake/jsk_robot_startupConfig.cmake:141 (message):
Project 'welcome_to_jsk_fetch' tried to find library 'jsk_robot_startup'.
The library is neither a target nor built/installed properly.  Did you
compile project 'jsk_robot_startup'? Did you find_package() it before the
subdirectory containing its code is included?
Call Stack (most recent call …
```

remove roseus find_package in welcome_to_jsk_fetch

---

jsk_maps/launch/start_empty_map.launch
jsk_maps/launch/start_map_empty_world.launch

rename `start_empty_map.launch` to `start_map_empty_world.launch` in order to standardize as other map launch.
other map launches' name are `start_map_[eng2|eng8].launch`, so the launch for `empty_world` should be `start_map_empty_world.launch`. 
the file name rule is used to launch in `pr2.launch` and `fetch_bringup.launch`.
I add symbolic link to keep the old filename launch, too.
https://github.com/jsk-ros-pkg/jsk_robot/blob/5c3fce88184e953ba753c83b53bdb07c806771eb/jsk_pr2_robot/jsk_pr2_startup/pr2.launch#L62
https://github.com/jsk-ros-pkg/jsk_robot/blob/5c3fce88184e953ba753c83b53bdb07c806771eb/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch#L185

[jsk_maps] rename start_empty_map.launch and standardize as other map launch

---

jsk_maps/src/dump-map-info.l
jsk_maps/tools/publish_scene.l

This PR fixes a bug in noetic environment.
In noetic environment, map doesn't adjust correct position defined by tf.
We have to remove the first character of slash from the frame_id in the launch files below that is made in catkin build, that is not tracked by git, probably because some minor changes have merged to tf2...
```xml
<launch>
<arg name="keepout" default="false"/>
<arg name="launch_map_server" default="true"/>
<group if="$(arg launch_map_server)">
<group if="$(arg keepout)">
<node name="$(anon map_server00)" pkg="map_server" type="map_server"
args="$(find jsk_maps)/raw_maps/eng2-7f-0.05_keepout.yaml" >
<remap from="map" to="/eng2/7f"/>
<param name="frame_id" value="/eng2/7f"/>
</node>
<node name="$(anon map_server01)" pkg="map_server" type="map_server"
args="$(find …
```

[Bugfix] [jsk_maps] Remove a slash from the first character of frame_id because map does not adjust map frame_id in noetic.
