jsk-ros-pkg/jsk_demos

detect_cans_in_fridge_201202/launch/startup.launch
face detection runs in default
=> [detect_cans_in_bridge_201202] remove hydro_detection.launch. 

jsk_2015_06_hrp_drc/drc_task_common/config/drc_task_common.rviz, jsk_2015_06_hrp_drc/drc_task_common/euslisp/request-ik-from-marker.l
主に機能の変更はないのですが，
こまなかバグをなくしつつ，プログラムを整理しました．
* rvizのconfigを最新のものに変更
* 関数を使って同じコードを短縮
* executable-mapからinverse-reachabilityに名前を変更
=> Clean programs

jsk_2015_06_hrp_drc/drc_task_common/euslisp/dynamic_reachability_publisher.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/request-ik-from-marker.l, jsk_2015_06_hrp_drc/drc_task_common/launch/robot_motion.launch
https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2015_06_hrp_drc/drc_valve_task/euslisp/reachability-map-publisher.l
で事前に作ってpublishしていたリーチャビリティマップを，動的に作るようにしました．
片手だけではなく両手で解いたり，ドリルの軸を固定した状態など，
様々な条件でリーチャビリティマップを得られるようになりましたが，
表示されるまでにかなりの時間がかかります．
一応，他のノードで計算するようにして，メインのプログラムの制御を奪わないようにしています．
=> Add dynamic reachability

jsk_2015_06_hrp_drc/drc_task_common/catkin.cmake, jsk_2015_06_hrp_drc/drc_task_common/config/drc_teleop_interface.ui, jsk_2015_06_hrp_drc/drc_task_common/euslisp/request-ik-from-marker.l, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/drc_teleop_interface.cpp, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/drc_teleop_interface.h, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/manipulation_data_server.cpp, jsk_2015_06_hrp_drc/drc_task_common/srv/GetIKArm.srv
grasp，push関係のコードに変更を加えました．
* ikの回数を，マップ作成時は少なく，実際に解く時には多くなるようにした．( https://github.com/jsk-ros-pkg/jsk_demos/pull/124 でのconversationより)
* 両手のハンドを別々にgraspできるようにした．ハンドは他のプログラムで参照してるハンドをサービスで取得する．
* graspのポーズを２種類にした．ドリル用とバルブ用
* 左手でものを抑えながら右手でボタンを押す，などができるようにした．
=> Add arm methods

jsk_2015_06_hrp_drc/drc_task_common/launch/operator_station_main.launch
manipulation_data_serverをlaunchに入れました。
=> add manipulation data server in operator station

jsk_2015_06_hrp_drc/drc_com_common/catkin.cmake, jsk_2015_06_hrp_drc/drc_com_common/launch/field_computer_com.launch, jsk_2015_06_hrp_drc/drc_com_common/launch/operator_station_com.launch, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSLarge.msg
@mmurooka Let me know you find any problem
=> [drc_com_common] Add script to stream data from FC to OCS

jsk_demo_common/euslisp/attention-observation.l
avoid loop check error throw when executing state which contains sub state machine.
=> support submachine in loop check

jsk_demo_common/euslisp/preemptive-task-execution.l, jsk_demo_common/sample/attention-observation-sample.l, jsk_demo_common/sample/preemptive-task-execution-sample.l
add preemptive task execution smach generator, its execution management module, and its sample code.
=> Add preemptive task execution

jsk_demo_common/README.md
add brief description and usage of sample codes.
=> add README.md

jsk_demo_common/euslisp/attention-observation.l
add sample directory for attention observation
=> add sample directory

jsk_2015_06_hrp_drc/drc_task_common/launch/teleop_device.launch
devicefile is no longer necessary.
=> Remove argument to set trackball device file

jsk_2015_06_hrp_drc/drc_task_common/config/hrp2_interactive_marker.yaml, jsk_2015_06_hrp_drc/drc_task_common/config/staro_interactive_marker.yaml, jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-task-common-util.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/eus-command-server.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/request-ik-from-marker.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/walk-to-object.l, jsk_2015_06_hrp_drc/drc_task_common/launch/drc_task_common.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/drc_task_common_hrp2.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/remote_server.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/robot_model.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/robot_motion.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/teleop_device.launch
Use drc_task_common_hrp2.launch for hrp2, and drc_task_common_staro.launch for staro.
=> Enable to switch target robot from launch file argument

jsk_maps/CMakeLists.txt, jsk_maps/package.xml
fix for https://github.com/jsk-ros-pkg/jsk_demos/issues/140
=> [jsk_maps] Disable X by unsetting DISPLAY variable during compilation to avoid init-x error on catkin build

jsk_2015_06_hrp_drc/drc_com_common/catkin.cmake, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSSmall.msg
Now it's only contains joint angles
=> [drc_com_common] Add special message for narrow band from FC to OCS.

jsk_2015_06_hrp_drc/drc_task_common/euslisp/hrp3hand-grasp.l
graspの成功が判定しつつ掴むプログラムです．
今のところは，失敗した時とのベクトルの距離が大きい時に成功としています．
=> add hrp3hand grasp and desicion function

jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-valve-motion.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/search-stand-position.l
add generate-valve-motion.l and search-stand-position.l to search rotatable position for valve and show ik success points on valve.
=> search rotatable position for valve

jsk_2015_06_hrp_drc/drc_com_common/catkin.cmake, jsk_2015_06_hrp_drc/drc_com_common/launch/field_computer_com.launch, jsk_2015_06_hrp_drc/drc_com_common/launch/operator_station_com.launch, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSLarge.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSSmall.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/OCS2FCSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/config/ocs_ui_button_layout.yaml, jsk_2015_06_hrp_drc/drc_task_common/drc_task_common.sh, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/util.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/go_pos_recog.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/go_pos_recog.launch~, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ui.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ui.launch~, jsk_2015_06_hrp_drc/drc_task_common/launch/operator_station_main.launch
first step of system integration towards DRC final
=> [drc_com_common, drc_task_common] Add image_view2 based user interface.

jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l, jsk_2015_06_hrp_drc/drc_task_common/package.xml
Simple state machine for UI and communication status.
The implementation is based on roseus_smach amd make it simpler by thin wrapper.
=> [drc_task_common] Add state machine class based on state-machine of roseus_smach

jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-valve-motion.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/search-stand-position.l
https://github.com/jsk-ros-pkg/jsk_demos/pull/167
=> Search rotatable position (merged with origin/master to pass test)

jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-valve-motion.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/search-stand-position.l
[invers-rv-map](https://cloud.githubusercontent.com/assets/6928359/6149170/27e39676-b24a-11e4-80f2-4c6e9f07abe2.png)
add color map of which color are defined by number of times of solved ik
=> add color map of reachbility

jsk_2015_06_hrp_drc/drc_task_common/config/drc_task_common.rviz, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-valve-motion.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-util.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l, jsk_2015_06_hrp_drc/drc_task_common/launch/drc_task_common_hrp2.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ui.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/operator_station_main.launch
Visualize current state of ocs.
We should be able to use smach but it's too complicated for our motivation...
=> [drc_task_common] Visualize current state of ocs state machine

jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSSmall.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/OCS2FCSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/util.l
=> [drc_task_common, drc_com_common] Add narrowband-message-handler to handle compact message between fc and ocs

jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSSmall.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/OCS2FCSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/config/ocs_ui_button_layout.yaml, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/util.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/valve_recognition.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch
=> [drc_task_common] Integrate valve detection

jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSSmall.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/OCS2FCSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/config/ocs_ui_button_layout.yaml, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/util.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/centroid_of_pointcloud_in_rect.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/door_recognition.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/stereo_preprocess.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/operator_station_main.launch
=> [drc_task_common, drc_com_common] Integrate Door detection

jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSSmall.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/OCS2FCSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/catkin.cmake, jsk_2015_06_hrp_drc/drc_task_common/config/ocs_ui_button_layout.yaml, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/util.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/debri_recognition.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/go_pos_recog.launch~, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch, jsk_2015_06_hrp_drc/drc_task_common/package.xml
=> [drc_task_common, drc_com_common] Integrate debri detection

jsk_2015_06_hrp_drc/drc_com_common/launch/fc_relay.launch, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSLarge.msg, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-valve-motion.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-util.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/valve_recognition.launch
=> [drc_task_common] Integrate valve motion

jsk_2015_06_hrp_drc/drc_com_common/catkin.cmake, jsk_2015_06_hrp_drc/drc_com_common/launch/field_computer_com.launch, jsk_2015_06_hrp_drc/drc_com_common/launch/operator_station_com.launch, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSSmall.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/HumanoidJointAngles.msg, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/launch/operator_station_main.launch
previous pull request is a mistake
=> [drc_com_common, drc_task_common] Send compressed joint angles from FC to OCS

jsk_2015_06_hrp_drc/drc_com_common/catkin.cmake, jsk_2015_06_hrp_drc/drc_com_common/launch/fc_relay.launch, jsk_2015_06_hrp_drc/drc_com_common/launch/field_computer_com.launch, jsk_2015_06_hrp_drc/drc_com_common/launch/operator_station_com.launch, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSBasicInfoSmall.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/catkin.cmake, jsk_2015_06_hrp_drc/drc_task_common/config/drc_task_common.rviz, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-basic-info-publisher.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-basic-info-subscriber.l, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main_fc.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/operator_station_main.launch
* use sudo for silverhammer scripts
* use 1-1023 ports for narrowband communcation
* add continuous communication to send robot joint angles over narrowband
=> [drc_task_common. drc_com_common] Use 1-1023 port for continuous communication

jsk_2015_06_hrp_drc/drc_task_common/launch/operator_station_main.launch
@mmurooka @YuOhara Be careful about this change
=> [drc_task_common] Remap tf and joint_states for ocs settings

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-door-task.l
=> Add test code for door open

jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l
@mmurooka Be careful about this change
=> [drc_task_common] Check if the next state is possible to move to in state machine

jsk_2015_06_hrp_drc/drc_task_common/euslisp/search-stand-position-for-debri.l
draw color-map to show ik-results for debri-task.
=> add search-stand-position-for-debri.l to get color-map for debri-task

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/panorama.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch
Panorama view, it's not yet ready to use but.
=> [drc_task_common] Add panorama view by using IntermitentImageAnnotator

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-door-task.l
Update door open testing codes.
Push + pull without door closer
=> Update door open testing codes (push + pull without door closer)

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-door-task.l
Add global pose variables and update function docs.
=> Add global pose variables and update function docs

jsk_2015_06_hrp_drc/drc_task_common/euslisp/hrp3hand-grasp.l
graspの結果を、予め覚えさせたテンプレートの中で一番近いものから選ぶようにしました。
キーワード変数:learnで新しい姿勢を覚えさせるように変更しました。
=> change construct of grasp-code

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
=> Add terrain walk functions.

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/package.xml
=> [drc_task_common] Add dependency to footstep planners

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update walking pose and fix function name．
=> Update walking pose and fix function name

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-door-task.l
Add push/pull verification for door open.
=> Add push/pull verification for door open

jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-drill-motion.l
almost same with generate-hose-motion
the diff is
* add grasp-up ik
* add drill-reset-pose
* changed default coords
=> add drill grasp motion generator

jsk_2015_06_hrp_drc/drc_task_common/config/ocs_ui_button_layout.yaml
need for https://github.com/jsk-ros-pkg/jsk_demos/pull/266, forget to add change.
=> [drc_task_common] change service name of drill-grasp button

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/drill_recognition_for_put.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/drill_recognition_sift.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/polygon_to_center_pose.py
ドリルの置く場所を指定するためのlaunch.
ユーザーが選択した領域のポイントクラウドの法線をとって，そのposeをpublishします．
=> Add recogniton for drill put place

jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch
https://github.com/jsk-ros-pkg/jsk_recognition/pull/729
がマージされると平面の向きが合って，ICPで合うようになります．
=> change to use icp for drill

jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/primitive-marker-util.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/drill_recognition.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/polygon_to_center_pose.py
https://github.com/jsk-ros-pkg/jsk_visualization/pull/334
の変更を反映させて，ドリルのcolladaモデルを使用するようにしました．
=> use drill urdf marker

jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/rviz_status.py
=> [drc_task_common] Change text color on rviz according to communication

jsk_2015_06_hrp_drc/drc_task_common/scripts/drill_button_publisher.py, jsk_2015_06_hrp_drc/drc_task_common/scripts/revise_button_position.py
change marker position with rviz_clicked_point.
=> Move marker with clicked point

jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-boundingbox.l
=> [drc_task_common] Add simple code to publish bounding box of robot

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/locomotion.launch
=> [drc_task_common] Estimate planar region of environment

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l
Add drc testbed models.
@s-noda 
Could you add your debri models?
=> Add drc testbed models

jsk_2015_06_hrp_drc/drc_task_common/scripts/gen_hosts.py
```
$ sudo sh -c './gen_hosts.py 13 ocs11 > /etc/hosts'
```
=> [drc_task_common] Add script to generate /etc/hosts for drc

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/drive.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/calc_drive_tf.py
=> remove dynamic tf remapping

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/drive.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/calc_drive_tf.py, jsk_2015_06_hrp_drc/drc_task_common/scripts/request_handle_marker.py
revise handle pose with marker
=> Static handle pose

jsk_2015_06_hrp_drc/drc_task_common/scripts/calc_drive_tf.py, jsk_2015_06_hrp_drc/drc_task_common/scripts/car_model_publisher.py
車の座標系が出るようになってきたので、
その座標系に車のモデルと予測進路線を表示するサンプルノードを加えました。
=> add car marker test code

jsk_2015_06_hrp_drc/drc_task_common/euslisp/debris.l
roseus debris.l
(view-random-debris)
@s-noda TODO: By using dynamics simulator, place debris randomly.
=> intial commit of debris.l, gen random position and attitude model

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l
Add argument to configure block dimensions and add getting face method.
=> Add argument to configure block dimensions and add getting face method

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update terrain methods and add terrain hrpsys simulation sample.
=> Update terrain methods and add terrain hrpsys simulation sample

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Added terrain walk simulation sample for staro version
=> Add staro version terrain walk simulation

jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-util.l
reach-until-touchで変位量が返ってくるように変更しました．
=> update reach until-touch to get displacement of the limb

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l
Add add-groud-p argument for terrain and stair models
=> Add add-groud-p argument for terrain and stair models

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Add roll offset for walking pose.
=> Add roll offset for walking pose

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l
Assoc link to robot-model and fix color
=> Assoc link to robot-model and fix color

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update stair model and walking poses and add stair testing codes.
=> Update stair model and walking poses and add stair testing codes

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
=> Add hrp2jsk sample

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/msg/Float32ArrayStamped.msg, jsk_2015_06_hrp_drc/drc_task_common/scripts/wrench_fft.py
=> add node to calc fft of wrench

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Added hrp2jsk version terrain walk simulation and supplemented simulator command utility warnings
=> Add hrp2jsk terrain walk simulation

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
=> Update hrp2 stair sample

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Add function to calculate leg reachability and base trajectory
=> Add function to calculate leg reachability and base trajectory

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update samplelaunch and auto-root-height function.
=> Update samplelaunch and auto-root-height function

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/locomotion.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/locomotion_planner.launch
Don't know why but cwd="node" is required to load compiled euslisp source code
=> [drc_task_common] Update locomotion parameters and add cwd option to coompile footstep_planner.l correctly

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update rtmsample and use angle vector sequence.
=> Update rtmsample and use angle vector sequence

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Use rleg coords instead of ee corods directly.
=> Use rleg coords instead of ee

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update baseheight calculation.
=> Update baseheight calculation

jsk_2015_06_hrp_drc/drc_task_common/README.md
Added documentation about how to utilize test-drc-terrain-walk simulation
=> Add document about test-drc-terrain-walk

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-drill-motion.l
=> add_new_takenoko_drill_model

jsk_2015_06_hrp_drc/drc_com_common/msg/OCS2FCSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/config/ocs_ui_button_layout.yaml, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-drill-motion.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-util.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/state-machine.l
model2realのタイミングでフラグが立っていたときにキャンセルできるようにしました．
=> Add cancel motion button

jsk_2015_06_hrp_drc/drc_task_common/config/drc_task_common.rviz, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/util.l, jsk_2015_06_hrp_drc/drc_task_common/scripts/rviz_status.py
ocs-exective.l でpublishされるRviz表示用文字の色分けなどをしました．
=> [drc_task_common] Arrange rviz text

jsk_2015_06_hrp_drc/drc_task_common/config/locomotion.rviz
@yoshimalucky Please use this rviz file
=> [drc_task_common] Add .rviz file for locomotion development

jsk_2015_06_hrp_drc/drc_com_common/launch/operator_station_com.launch, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSBasicInfoSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-basic-info-publisher.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-basic-info-subscriber.l, jsk_2015_06_hrp_drc/drc_task_common/launch/operator_station_main.launch
This is super important to see correct pointcloud...
=> [drc_task_common] Hot fix to use hrp2016 latest model

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle/LocalPlannerMochikaeParams.cfg, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle/ObstacleDetectionParams.cfg, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle/PassthroughCarBody.cfg, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle/SwitchInputCloud.cfg, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle/VisualOdometryVerification.cfg, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle/viso2_params.yaml, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/extract_obstacle_cloud.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/local_planner_mochikae.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/multisense_rosbag_static_tf_publisher.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/obstacle_detection.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/passthrough_car_body.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/real_viso2_steering_verification.launch, jsk_2015_06_hrp_drc/drc_task_common/msg/Int8Float64.msg, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/Magnetometer2Direction.py, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/real_staro_drive_recognition.sh, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/input_cloud_switching.cpp, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/kdtree_obstacle_detection.cpp, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/passthrough_car_body.cpp, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/simplified_local_planner_mochikae.cpp, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/visual_odometry_verification.cpp
These programs were in drive_recognition before.
@terasawa  please check.
=> Add recognition programs for vehicle task to drc_task_common

jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-drill-motion.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l
変更点
* undifined variables のバグをなくしました(arms->:arms)
* ドリルのタイプが古いものが渡されていたので、:takenokoにしました。ちゃんとドリルのタイプを規定した変数が下の関数まで行ってない可能性があったので、ひとまずちゃんと動くようにコメントアウトしました。
=> Comment out drill type

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/extract_obstacle_cloud.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/SteeringAngleMarker.py
modify include path in launch file and add SteeringAngleMarker.py for using drive recognition program
=> modify launch and add steering_angle_marker for drive recognition

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/hrp2jsk-driving-motion-on-polaris-xp900.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/hrp2jsknt-driving-controller-on-polaris-xp900.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/robot-driving-motion.l
- move drive-init-pose-support-by-leg to robot-driving-motion
- default stop-impedance to nil in approach-handle
- waist-p 0 -> 10 in drive-init-pose
=> Add some changes for new seat (testbed version) of drc vehicle.

jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-util.l
For https://github.com/jsk-ros-pkg/jsk_demos/issues/425.
This contains https://github.com/jsk-ros-pkg/jsk_demos/pull/428.
=> [drc_task_common] fix get-potentio-vector-from-ocs

jsk_2015_06_hrp_drc/drc_task_common/README.md
Update hrp2 model path in README.
=> Update hrp2 model path in README

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/plugin.xml, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/vehicle_ui, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/vehicle_ui.py, jsk_2015_06_hrp_drc/drc_task_common/srv/SetValue.srv
=> [drc_task_common] Add vehicle UI

jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/vehicle_ui.py
=> Fix typo: ImageWidget->ROSImageWidget for multisense_widget

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle.launch
@orikuma 
Use /handl_pose and /crank_pose
=> [drc_task_common] Add vehicle.launch and add handle detection based on marker

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle.launch, jsk_2015_06_hrp_drc/drc_task_common/package.xml
=> [drc_task_common] Use circle dot patterns instead of ar marker as handlemarker

jsk_2015_06_hrp_drc/drc_task_common/euslisp/request-ik-from-marker.l
JAXONで足が伸びきらないようにHRP2と同様のパラメータを加えました．
=> [drc_task_common] fix root joint min parameter for jaxon

jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-drill-motion.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/scripts/drill_button_publisher.py
* ikのJAXON対応
* 探索範囲を小さくする
* 座標変換で微妙に間違ってるところを直す
* ドリルを置くときに、平面が上をみるように変更。(認識では必ず平面から上向き（法線方向）に出る気がするが、人がインタラクティブマーカーで動かした時に逆向きにしてしまうのを防ぐため）
=> Change drill motion 0420

jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-valve-motion.l
- ccw rotation
- enable to select center grasp
- add jaxon sample
=> [jaxon_ros_bridge] improve jaxon valve

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
@k-kimura is this what you mean?
=> forget to use deg2rad

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-door-task.l
=> add jaxon 1m lateral walk parameters

jsk_2015_06_hrp_drc/drc_task_common/README.md, jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update terrain samples and readme.
=> Update terrain sample

jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/machines/HRP2JSK.machine, jsk_2015_06_hrp_drc/drc_task_common/launch/machines/HRP2JSKNT.machine, jsk_2015_06_hrp_drc/drc_task_common/launch/machines/JAXON.machine
load `$(find drc_task_common)/launch/machines/$(env ROBOT).machine` file on the top of field_computer_main.launch
=> [drc_task_common] Add machine tags

jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/util.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/drill_recognition.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/stereo_preprocess.launch
Add jsk_topic_tools/Passthgough to drill detection to reduce CPU load and remove voxel grid downsampling in stereo_preprocess.launch
to supress warning message
=> [drc_task_common] Add jsk_topic_tools/Passthgough to drill detection to

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/robot-driving-controller.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/robot-driving-motion.l
I hope this solution solves interpolation problem in handling
=> Add turn-handle-velocity, control by angle-velocity and only use angle-vector (not angle-vector-sequence) in turn-handle

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/valve_recognition.launch
set min_radius of valve recognition 0.05
=> [drc_task_common] Change min radius of valve recognition

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/hrp2jsk-driving-controller-on-polaris-xp900.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/hrp2jsknt-driving-controller-on-polaris-xp900.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/hrp2jsknts-driving-controller-on-polaris-xp900.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/jaxon-driving-controller-on-polaris-xp900.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/robot-driving-controller.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/staro-driving-controller-on-polaris-xp900.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/staro-driving-controller.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/handle_pose_detector.launch
To test vehicle task normally, I assumed to execute only following command: 
```bash
roslaunch drc_task_common vehicle.launch ROBOT:="robotname"
```
=> Provide launch file for vehicle task

.gitignore, jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/cfg/StandingDrillDetector.cfg, jsk_2015_06_hrp_drc/drc_task_common/include/drc_task_common/standing_drill_detector.h, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/drill_standing.launch, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/standing_drill_detector.cpp
=> [drc_task_common] Add standing drill detector

jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch
I have overdone adding 'if=false' , sorry...
=> fix overdone if=false

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update for hrp2jsk terrain walk.
=> Update hrp2jsk terrain walk

jsk_2015_06_hrp_drc/drc_com_common/launch/field_computer_com.launch, jsk_2015_06_hrp_drc/drc_com_common/launch/operator_station_com.launch, jsk_2015_06_hrp_drc/drc_com_common/package.xml
Usage:
```
rosrun roseus_remote remote-roseus-client.l
(list 1 2 3)
=> (1 2 3) ;; evaled in local
($ (list 1 2 3))
=> (1 2 3) ;; evaled in remote
```
`$` is a special macro to send s-expression to remote server
=> [drc_com_common] Add roseus_remote

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/locomotion.launch
see https://github.com/jsk-ros-pkg/jsk_recognition/pull/909
=> [drc_task_common] Use jsk_pcl/NormalEstimationOMP in locmotion.launch to solve timestamp problem

jsk_2015_06_hrp_drc/drc_task_common/euslisp/check-hand-grasp-coords.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-drill-motion.l
センサデータを元に手作業でモデルを合わせてパラメータを取得するノードを書いて、
それを反映させました。
=> [drc_task_common] add check-grasp-coords coords

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle/LocalPlannerParams.cfg, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/local_planner.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/real_staro_drive_recognition.sh, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/simplified_local_planner.cpp, jsk_2015_06_hrp_drc/gazebo_drive_simulator/README.md
remove function of "mochikae" and other unnecessary function for refactoring.
=> change file name and remove function of mochikae

interactive_behavior_201409/euslisp/main.l, interactive_behavior_201409/euslisp/pr2-behavior-utils.l
split conversion functions into `pr2-behavior-utils.l`
=> [interactive_behavior_201409] utilize look at funcs

interactive_behavior_201409/euslisp/main.l, interactive_behavior_201409/euslisp/pr2-behavior-utils.l
add /people topics (tracking data from leg_detector) to look at.
=> [interactive_behavior_201409] add /people to look at

elevator_move_base_pr2/CMakeLists.txt, elevator_move_base_pr2/launch/check_elevator_open.xml, elevator_move_base_pr2/launch/elevator_move_base_modules.xml, elevator_move_base_pr2/package.xml, elevator_move_base_pr2/src/elevator-move-base-main.l, elevator_move_base_pr2/src/find-elevator-button.l, elevator_move_base_pr2/src/move-inside-elevator.l, elevator_move_base_pr2/src/navigation-client.l
add feature to check if elevator is open by using octree change detector
This was checked by PR1012 (--from-full-source environment)
=> [elevator_move_base_pr2] add move-inside state machine that uses octree point cloud

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/extract_obstacle_cloud.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/local_planner.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/SteeringAngleMarker.py
不必要な部分を削りました。
これからトピック名を整理するので、
まだmergeしないでください。
=> omit unnecessary function and remove comment

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_path_visualizer.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/extract_obstacle_cloud.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/local_planner.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/obstacle_detection.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/passthrough_car_body.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/kdtree_obstacle_detection.cpp, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/simplified_local_planner.cpp
change topic name (add /drive/recognition) to make a distinction easily
=> add /drive/recognition in topic name

jsk_2015_06_hrp_drc/gazebo_drive_simulator/scripts/start_gazebo_drive_simulator.sh
remove recognition in gazebo drive simulator script
=> remove recognition script

jsk_2015_06_hrp_drc/gazebo_drive_simulator/README.md
add command of recognition for script in README
=> add script command

jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch
add lauch image_view for fisheye
=> add fishey image_view

jsk_2015_06_hrp_drc/gazebo_drive_simulator/README.md
=> Update README.md of gazebo_drive_simulator

jsk_2015_06_hrp_drc/gazebo_drive_simulator/launch/gazebo_drive_simulator.launch, jsk_2015_06_hrp_drc/gazebo_drive_simulator/patch/drc_final_task_1.patch
DRC Finalのtask 1のシミュレーション用の環境を作りました
=> add drc final task 1 for drive simulation

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/door_recognition.launch
@mmurooka Please use this parameters
=> [drc_task_common] Update recognition parameters for las vegas door

jsk_2015_06_hrp_drc/drc_com_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_com_common/launch/vehicle_field_computer_com.launch, jsk_2015_06_hrp_drc/drc_com_common/launch/vehicle_operator_station_com.launch, jsk_2015_06_hrp_drc/drc_com_common/msg/VehicleFC2OCSSmall.msg, jsk_2015_06_hrp_drc/drc_com_common/msg/VehicleOCS2FCSmall.msg, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/vehicle-executive-utils.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/vehicle-fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/vehicle-ocs-executive.l
Only pass handle_cmd and accel_cmd
=> Correspond vehicle task to silverhammer as a test

jsk_2015_06_hrp_drc/gazebo_drive_simulator/README.md
update README for spliting fc function or recommend to change world file
=> update README for spliting fc function

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_center_tf_publisher.launch, jsk_2015_06_hrp_drc/gazebo_drive_simulator/launch/gazebo_drive_simulator.launch
add tf "car_center" for static tf publisher.
We should  change this into dynamic tf publisher after checking marker program for grasping steering wheel.
=> add tf car_center launch

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt
Do not download models on travis in order not to fail building test
=> [drc_task_common]Do not download models on travis

jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/simplified_local_planner.cpp
fix bool of step_on_flag for bridge of motion and recognition
=> fix bool of step on flag

jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py
change height of predicted path marker from 0.4 to 0
=> change marker height to zero

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/valve_recognition.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/nearest_box_indices.py
=> [drc_task_common] Use laser pointcloud to detect valve

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/laser_preprocess.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/field_computer_main.launch
especially about laser preprocess
=> [drc_task_common] Support USE_LOCALHSOT argument to run code on localhost

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/car_center_publisher.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_center_tf_publisher.launch
publish tf "car_center" from marker posestamped
=> Posestamped to tf

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
=> add chest offset parameters to waking-pose

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
=> update jaxon stair parameters

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/car_center_publisher.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_center_tf_publisher.launch
I forgot to add dynamic_tf_publisher node, so add the node.
I also add default dynamic tf car_center in case the robot fails to recognize marker
=> add dynamic reconfigure and make defualt car_center

.travis.yml
question is : which is more reliable, compile pcl code on travis or using jenkins @ jsk, whcih is not physically accessable during fron next week
=> [.travis.yml] use jenkins for hydro

jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-drill-motion.l
=> [drc_task_common] drill task modification 20150517

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/visualize_local_planner_viso2.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/Magnetometer2Direction.py, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/drive_recognition.sh, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/simplified_local_planner.cpp
add command of publishing flag for rosbag and remove comment for processing more quickly
=> add rostopic pub for rosbag

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_center_tf_publisher.launch
add checkerboard detector of car_marker in launch file
=> add checkerboard detector for car_center

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle/ObstacleIndicatorParams.cfg, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_path_visualizer.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/driver_assist.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/drive_recognition.sh, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/obstacle_indicator.cpp
add obstacle length indicator in order to assist drivers
=> add obstacle indicator to assist drivers

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Add hrp2jsknts terrain function.
=> Add hrp2jsknts terrain function

jsk_2015_06_hrp_drc/drc_task_common/README.md
=> Update readme for terrain

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/car_center_publisher.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_center_tf_publisher.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/extract_obstacle_cloud.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/local_planner.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/obstacle_detection.launch
modify car_marker paent link from left_camera_optical_frame to BODY
=> Modify tf marker

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/hrp2-car_center-publisher.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/jaxon-car_center-publisher.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_center_tf_publisher.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/driver_assist.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/extract_obstacle_cloud.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/drive_recognition.sh, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/obstacle_indicator.cpp, jsk_2015_06_hrp_drc/gazebo_drive_simulator/launch/atlas_drc_practice_task_1.rviz
change parameter of static tf and passthrough height in order to remove things except obstacles
=> change parameter of static tf and passthrough height

jsk_2015_06_hrp_drc/drc_task_common/README.md, jsk_2015_06_hrp_drc/drc_task_common/patch/catkin_packages.patch
It's a hot fix for roslaunch to speed up.
It's not yet applied to upstream(roslaunch)
=> [drc_task_common] Add patch to speed up roslaunch

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/driver_assist.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/extract_obstacle_cloud.launch, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/obstacle_indicator.cpp
change remap because advertise remap was not working well
=> change remap in c++

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/multisense_rosbag_static_tf_publisher.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/drive_recognition.sh, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/obstacle_indicator.cpp, jsk_2015_06_hrp_drc/gazebo_drive_simulator/launch/atlas_drc_practice_task_1.rviz
change base frame of marker, from car_center to BODY for convenience
=> change base_tf from car_center to BODY

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l
=> Added test-field stair model.

jsk_2015_06_hrp_drc/drc_com_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_com_common/msg/FC2OCSLarge.msg, jsk_2015_06_hrp_drc/drc_com_common/package.xml, jsk_2015_06_hrp_drc/drc_task_common/config/vehicle_operator.rviz, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/robot-driving-controller.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/vehicle-ocs-executive.l, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle_fc.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/vehicle_ocs.launch
This PR changes FC2OCSLarge.msg. If size of topic is too large, MarkerArray needs to be reduced.
=> Pass rviz topics for rviz into silverhammer

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/ocs_car_center_publisher.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py
delete print debug and add ocs car_center
=> delete print debug and add ocs car_center

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l
Add function to make testfield stair (thanks for @yoshimalucky and @otsubo).
=> Add function to make testfield stair

jsk_2015_06_hrp_drc/drc_task_common/README.md, jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update terrain stair sample and readme
=> Update terrain stair sample and readme

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
=> add nakashima-stairs test program

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/door_unvisible_handle_recognition.launch
=> [drc_task_common] Update recognition parameter for door handle detector

jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/obstacle_indicator.cpp
change path visualizer parameter
=> change path visualizer parameter

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update for hrp2jsknt terrain sample.
=> Update for hrp2jsknt terrain sample

jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/hrp2-car_center-publisher.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/vehicle/jaxon-car_center-publisher.l
change timestamp of default tf "car_center" from (ros::time 0) to (ros::time-now)
=> change timestamp from ros::time 0 to ros::time-now

jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py
modify coorinates transformation of predicted path marker, adding rotation matrix
=> modify coorinates transformation of predicted path marker

jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/obstacle_indicator.cpp
add quadratic function in steering angle and curvature table
=> add quadratic function in table

jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l
=> [drc_task_common] Update valve request timing

jsk_2015_06_hrp_drc/drc_task_common/CMakeLists.txt, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/driver_assist.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/extract_obstacle_cloud.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/passthrough_car_body.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/obstacle_indicator.cpp, jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/passthrough_car_body.cpp
finish processing when finishing task1 by subscribing execute_flag
=> finish processing when finishing task1

jsk_2015_06_hrp_drc/drc_task_common/README.md, jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Add stair check for hrp2jsknts.
=> Add stair check for hrp2jsknts

jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-robot-interface.l
=> fix msg instantiation args type

jsk_2015_06_hrp_drc/drc_task_common/scripts/joy_to_twist.py
=> revise joy

jsk_2015_06_hrp_drc/drc_task_common/scripts/vehicle/car_path_visualizer.py
=> change default flag

jsk_2015_06_hrp_drc/drc_task_common/euslisp/drc-testbed-models.l
=> Update final stair

jsk_2015_06_hrp_drc/drc_task_common/euslisp/ocs-robot-interface.l
=> def go-pos in ocs-ri

jsk_2015_06_hrp_drc/drc_task_common/euslisp/robot-util.l
遷移時間など実機（VIOLET）で確認しました．
https://github.com/jsk-ros-pkg/jsk_demos/pull/922
バッテリーがなくなりかけた時に平地に移動してこのポーズを送ってリレーを落とすことができると思います．
=> add emergency pose function : supporting jaxon and jaxon_red

jsk_2015_06_hrp_drc/drc_task_common/euslisp/fc-executive.l
https://github.com/jsk-ros-pkg/jsk_demos/pull/921
=> implement emergency button

jsk_2015_06_hrp_drc/drc_task_common/scripts/check_sanity_fc.py
DON'T MERGE UNTIL https://github.com/jsk-ros-pkg/jsk_common/pull/981 MERGED
=> add git check sanity fc

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/car_center_tf_publisher.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/vehicle/driver_assist.launch
respawnをつけたのでマージしてください．そしてFCをアップデートしたいです．
=> add respawn in drive recognition launch

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/drill_recognition.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/static_transform_bounding_box_array.py
立っているドリルが見つからなくなっていたので，見つかるように変えました．
=> change params to detect standing drill

jsk_2013_04_pr2_610/launch/demo_all.launch, jsk_2013_04_pr2_610/launch/demo_common.launch, jsk_2013_04_pr2_610/launch/demo_tray.launch, jsk_2013_04_pr2_610/launch/demo_wash.launch, jsk_2013_04_pr2_610/launch/detect_all.launch, jsk_2013_04_pr2_610/launch/detect_with_image.launch
`roslaunch jsk_2013_04_pr2_610 demo_all.launch use_sim:=true`
To launch on only local machine not pr2.
=> [jsk_demos/jsk_2013_04_pr2_610] add use_sim option to launch files for launching on non PR2 environment

jsk_2015_06_hrp_drc/drc_com_common/launch/field_computer_com.launch, jsk_2015_06_hrp_drc/drc_com_common/launch/operator_station_com.launch, jsk_2015_06_hrp_drc/drc_com_common/package.xml
see https://github.com/jsk-ros-pkg/jsk_common/pull/1018
=> [drc_com_common] Use jsk_robot_utils to compress/decompress joint angles

detect_cans_in_fridge_201202/launch/perception.launch
=> [jsk_demos] fix typo

detect_cans_in_fridge_201202/launch/perception.launch
change by jsk-ros-pkg/jsk_robot#364
=> [detect_cans_in_fridge] change from openni_c2 to kinect_head_c2

jsk_2015_06_hrp_drc/drc_task_common/launch/fc/laser_preprocess.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/stereo_preprocess.launch
laser_preorocess.launch with jsk_topic_tools/standalone_complexed_nodelet
=> [drc_task_common] Rewrite stereo_preprocess.launch and

detect_cans_in_fridge_201202/launch/perception.launch
remap name was wrong. So modify.
=> [detect_cans_in_fridge] modify launch remap

detect_cans_in_fridge_201202/launch/perception.launch, jsk_demo_common/euslisp/pr2-action.l, jsk_demo_common/euslisp/pr2-move.l
At present, 2 function is being divided.
* goto-front-of-fridge (finished)
* open-fridge-door  (yet)
=> DO NOT MERGE YET

jsk_2013_04_pr2_610/euslisp/move-chair.l, jsk_2013_04_pr2_610/euslisp/pick-broom.l, jsk_2013_04_pr2_610/euslisp/pick-cloth.l, jsk_2013_04_pr2_610/euslisp/pick-tray.l, jsk_2013_04_pr2_610/euslisp/put-cloth-into-laundry.l, jsk_demo_common/euslisp/pr2-action.l
related to the critical mistake in #1008 .
=> [jsk_demo_common] fix error in simulation-modep part

detect_cans_in_fridge_201202/euslisp/color_histogram_creater.l
Please review @YoheiKakiuchi
Also do you remember how to use this? @himlen1990 (Li Zijia) willing to use this
Cf: https://github.com/jsk-ros-pkg/jsk_demos/commit/2725e0e81b595fdf01db2b88f4c3611b474ab0ac#commitcomment-12615668
=> euslisp/color_histogram_creater.l: use eus-pointcloud instead of 3dpointcloud

detect_cans_in_fridge_201202/euslisp/color_histogram_creater.l
@himlen1990 @aginika 
You can try commands below after loading color_histogram_creator.l
~~~
(init-setting) ;; initialization
(setq hist (create-hist 8 10 10)) ;; crate histogram list, you should put a object on PR2's hand.
(divided-pcl-vis *lst*) ;; view results
~~~
https://github.com/jsk-ros-pkg/jsk_demos/issues/1027
https://github.com/jsk-ros-pkg/jsk_demos/pull/1032
=> add documentation string

detect_cans_in_fridge_201202/launch/perception.launch
add visualising GaussianPointCloud of fridge to fridge demo launch
=> [detect_cans] visualize GaussianPointCloud of fridge

detect_cans_in_fridge_201202/launch/startup.launch
=> [detect_cans] fix arg in startup.launch

jsk_2015_06_hrp_drc/drc_task_common/euslisp/walk-to-object.l, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ocs_rviz.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/robot_motion.launch
tfなど を remapしないでocs_rviz.launch
のみで完結するオプションを加えました。
=> add option for not use ocs remap

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-door-task.l
add use-leg option to param-door.
=> add use-leg option to param-door

detect_cans_in_fridge_201202/euslisp/main.l
=> [detect_cans] set *current-context*

detect_cans_in_fridge_201202/euslisp/fridge-demo-smach-main.l, detect_cans_in_fridge_201202/euslisp/main.l, jsk_demo_common/euslisp/pr2-action.l, jsk_demo_common/euslisp/pr2-move.l
exec fridge demo in simulation mode 
exec fridge demo  in smach version
=> Exec fridge demo in simulation mode

jsk_2015_06_hrp_drc/drc_task_common/jvrc_fc.sh, jsk_2015_06_hrp_drc/drc_task_common/jvrc_ocs.sh, jsk_2015_06_hrp_drc/drc_task_common/launch/fc/locomotion.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ocs_executive.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ocs_locomotion.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ocs_locomotion_planner.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ocs_rviz.launch
drc_task_commonのlocomotionをjvrc用に少し変えました。
imuを
https://github.com/YuOhara/jsk_demos/blob/locomotion_in_jvrc_new/jsk_2015_06_hrp_drc/drc_task_common/launch/fc/locomotion.launch#L4
のようにmultisenseのimuを、STANDALONEでないときにはあげないようにしたので、DRCプログラムにも少し影響があるかもしれないです。
=> Locomotion in jvrc new

jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ocs_rviz.launch, jsk_2015_06_hrp_drc/drc_task_common/launch/transformable_model.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/b_control_client.py
oneclickでjvrcのシリンダーが見つかるようにしました
=> [drc_task_common] one click cylinder detection

jsk_2015_06_hrp_drc/drc_task_common/jvrc_fc.sh
@YoheiKakiuchi ここにおくつもりでした。よければテスト通ったらmergeお願いします
=> Add multisense launch

jsk_2015_06_hrp_drc/drc_task_common/config/object_marker_command.yaml, jsk_2015_06_hrp_drc/drc_task_common/euslisp/request-ik-from-marker.l, jsk_2015_06_hrp_drc/drc_task_common/launch/transformable_model.launch
https://drive.google.com/file/d/0B5Du3wvWhb-uamYyOGtJajEwMGM/view?usp=sharing
=> [drc_task_common] add always-ik-mode

jsk_2015_06_hrp_drc/drc_task_common/config/ocs_ui_jvrc_cheat.yaml, jsk_2015_06_hrp_drc/drc_task_common/jvrc_ocs.sh, jsk_2015_06_hrp_drc/drc_task_common/launch/ocs/ui.launch
jvrc用の約３倍速で歩くcheatモードのボタンを増やしました
=> add cheating speedup mode for jvrc

jsk_2015_06_hrp_drc/drc_task_common/euslisp/jvrc-grasp-spreader.l
change walking parameter and modify hold-spreader for speed-up
=> modify for speed-up in jvrc task R3A

jsk_2015_06_hrp_drc/drc_task_common/jvrc_fc.sh
https://github.com/start-jsk/rtmros_choreonoid/issues/100
ということがあるので、optionを追加しました。
=> add option not use resize for local usage

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Add hrp2jsknt block climbup demo
=> Add hrp2jsknt block climbup demo

jsk_2015_06_hrp_drc/drc_task_common/euslisp/jvrc-grasp-spreader.l
=> Add jvrc grasp spreader

jsk_2015_06_hrp_drc/drc_task_common/euslisp/jvrc-grasp-spreader.l
=> stop-impedance when using spreader

README.md, jsk_2013_04_pr2_610/README.md
ref: https://github.com/jsk-ros-pkg/jsk_demos/issues/1079
=> [README] update jsk_2013_04_pr2_610 demo readme

elevator_move_base_pr2/launch/elevator_move_base_modules.xml
ref: https://github.com/euslisp/jskeus/issues/287
=> [elevator_move_base_pr2/launch/elevator_move_base_modules.xml] use rectified image on light detect

interactive_behavior_201409/CMakeLists.txt
assumed merging after https://github.com/jsk-ros-pkg/jsk_demos/pull/1103
this PR should passes the test.
=> [interactive_behavior_2014_09/CMakeLists.txt] not require face_recognition on find_package

jsk_2013_04_pr2_610/CMakeLists.txt, jsk_2013_04_pr2_610/package.xml, jsk_2013_04_pr2_610/test/test-demo.l, jsk_2013_04_pr2_610/test/test-demo.test, jsk_demo_common/CMakeLists.txt, jsk_demo_common/package.xml
前のgo-posを変えた影響かわからないけど，上のように冷蔵庫を飛び越さない？ 
あと，これのsmach版もtestしたいのと，
冷蔵庫のデモのテストも同じように作ってみて下さい　> @h-kamada
=> add rostest for demo program

jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-drill-motion.l
jaxonの首まわりの可動範囲が変わったようなので、
* 決め打ちの関節角を調整
* lookatでミスってたので、ひとまずlookatしないように調整
しました。
=> renew drill motion

jsk_2015_06_hrp_drc/drc_task_common/euslisp/generate-valve-motion.l
=> [drc_task_common] make slow valve motion a little

jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex_carry_trass/trass.l
=> [irex_carry_trass] update trass

jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex_carry_trass/carry-trass.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex_carry_trass/primitive-marker-for-trass.l
=> Trass with pfilter

jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex-large-box/reach.l
Changed push emergency stopper threshold parameter to 100N
=> change push emergency stopper threshold parameter to 100N

jsk_2015_06_hrp_drc/drc_task_common/scripts/imprecise_scheduler.py
Imprecise scheduling to decide suitable parmaeter based on deadline and quality-time table.
=> [drc_task_common] Add imprecise scheduler prototype

jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex-large-box/reach.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex-large-box/sift-box.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex_carry_trass/irex_demo.l
update for version Irex 20151202 final by k-kimura, koyama, youhei.
=> Irex 20151202 final

detect_cans_in_fridge_201202/README.md
=> [detect_cans] add README

jsk_2015_06_hrp_drc/drc_task_common/euslisp/primitive-marker-util.l
primitive-markerのTFの待ち時間のバ不具合が修正されました
=> [drc_task_common/euslisp/primitive-marker-util.l]

jsk_2015_06_hrp_drc/drc_task_common/euslisp/conservative-door-detection.l, jsk_2015_06_hrp_drc/drc_task_common/launch/conservative_door_detection.launch, jsk_2015_06_hrp_drc/drc_task_common/scripts/door_handle_bbox_extractor.py, jsk_2015_06_hrp_drc/drc_task_common/scripts/front_plane_extractor.py
(it takes 17 secs to detect door)
=> [drc_task_common] Add door handle detector with super conservative way

jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex_carry_trass/irex_demo.l, jsk_2015_06_hrp_drc/drc_task_common/euslisp/irex_carry_trass/primitive-marker-for-trass.l
Test large step stride while trass walking.
Set red color for iteractive marker.
=> Update trass demo

detect_cans_in_fridge_201202/euslisp/detect_cans.l, detect_cans_in_fridge_201202/euslisp/main.l, detect_cans_in_fridge_201202/launch/detect_cans.launch, detect_cans_in_fridge_201202/launch/gazebo_startup.launch, detect_cans_in_fridge_201202/launch/perception.launch, detect_cans_in_fridge_201202/launch/startup.launch
you can execute detect cans demo by
`roslaunch detect_cans_in_fridge_201202 gazebo_startup.launch`
**NOTE**
This PR is assumed to be merged after #1154
=> [detect_cans_in_fridge_201202/launch/gazebo_startup.launch] add launch file for gazebo

jsk_2015_06_hrp_drc/drc_task_common/launch/robot_model.launch
with https://github.com/jsk-ros-pkg/jsk_visualization/pull/561
=> [robot_model.launch] use upstream launch file

detect_cans_in_fridge_201202/launch/perception.launch
=> [detect_cans] [perception.launch] add can stocker

elevator_move_base_pr2/CMakeLists.txt
to fix https://travis-ci.org/jsk-ros-pkg/jsk_robot/jobs/114804561
=> add catkin_INCLUDE_DIRS to elevator_move_base_pr2

detect_cans_in_fridge_201202/euslisp/main.l, detect_cans_in_fridge_201202/euslisp/pddl-action.l, detect_cans_in_fridge_201202/launch/planner.launch, jsk_demo_common/euslisp/pr2-action.l
tested on PR1012.
required other PRs:
- https://github.com/jsk-ros-pkg/jsk_planning/pull/43
- https://github.com/jsk-ros-pkg/jsk_planning/pull/44
=> [detect_cans_in_fridge_201202] enable fridge demo pddl version

jsk_2015_06_hrp_drc/drc_task_common/euslisp/test-drc-terrain-walk.l
Update hrp2jsk stair function.
=> Update hrp2jsk stair function.

jsk_2015_06_hrp_drc/drc_task_common/launch/conservative_valve_detection.launch
Default behavior is not changed
=> Add some arguments  to modify some parameters from other launch

detect_cans_in_fridge_201202/package.xml
=> [detect_cans_in_fridge_201202] add interactive_behavior_201409 to run_depend

jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/standing_drill_detector.cpp
see
- https://github.com/jsk-ros-pkg/jsk_common/pull/1462
- https://github.com/jsk-ros-pkg/jsk_common/issues/1461
=> Stop using deprecated jsk_topic_tools/log_utils.h

jsk_maps/CMakeLists.txt
fix for https://github.com/jsk-ros-pkg/jsk_common/issues/1488#issuecomment-262935049
=> add ARCHDIR for LinuxARM

jsk_maps/.gitignore, jsk_maps/CMakeLists.txt, jsk_maps/README.md, jsk_maps/launch/start_map_eng2.launch, jsk_maps/launch/start_map_eng8.launch, jsk_maps/src/catkin-build-util.l, jsk_maps/src/dump-map-info.l
- use ros path for generated launch files
- added option `launch_map_server` for generated launch files
- use `xml` extension for generated launch files not to be launched by `roslaunch` directly
- cleaned up codes
- added README
=> [jsk_maps] improve jsk maps

jsk_maps/src/building-model.l
add method to find current room for object / robot
e.g.:
```lisp
(load "package://jsk_maps/src/eng2-scene.l")
(load "package://pr2eus/pr2.l")
(setq *scene* (make-eng2-scene))
(setq *robot* (pr2))
(send *robot* :transform (send (send *scene* :spot "/eng2/7f/room73B2-fridge-front") :copy-worldcoords))
(send *scene* :current-room *robot*)
;; => "/eng2/7f/73b2"
```
=> [jsk_maps][building-model.l] add :rooms / :current-room

jsk_maps/tools/publish_spot.l
for https://github.com/jsk-ros-pkg/jsk_robot/pull/754#issuecomment-290035350
cc: @furushchev
=> jsk_maps/tools/publish_spot.l: add message when map is selected

jsk_2017_10_semi/CMakeLists.txt, jsk_2017_10_semi/package.xml
=> Remove unnecessary build_depend and fetcheus for kinetic build

jsk_maps/src/eng2-scene.l
fetchのdockの場所が再び変わったので、spotの位置も変えました。
=> update position of fetch's charge dock

diabolo_pr2_201806/config/idle-diabolo.rviz, diabolo_pr2_201806/euslisp/idle.l, diabolo_pr2_201806/euslisp/juggle.l
研究室見学の際の認識結果のビジュアライズのために.rvizファイルを用意しました．
=> 認識結果描画用の.rivzの追加と，リモコンでフィードバックコントロールを切る機能の追加

jsk_maps/README.md
=> fix a typo in REAME.md of jsk_maps

jsk_maps/src/eng2-scene.l
I update fetch dock spot place for current place
=> update fetch dock spot

jsk_2013_04_pr2_610/README.md, jsk_2013_04_pr2_610/jsk_2013_04_pr2_610.rosinstall, jsk_2013_04_pr2_610/launch/demo_all.launch, jsk_2013_04_pr2_610/launch/demo_common.launch, jsk_2013_04_pr2_610/launch/demo_tray.launch, jsk_2013_04_pr2_610/launch/demo_wash.launch
add melodic support for tutorials for jsk newcomers.
=> [WIP][jsk_2013_04_pr2_610] update README.md for melodic

jsk_2013_04_pr2_610/README.md
家事支援動作デモのREADMEのrosinstallのURLを修正しました。
=> fix readme rosinstall url

jsk_2019_10_semi/README.md
I edited the way how to get ros parameter.
=> edit how to get parameter in 2019 semi

jsk_2020_10_semi/uml/amabe.uml
=> add amabe.uml

.github/workflows/config.yml
need to fix
```
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Err https://esm.ubuntu.com trusty-infra-security/main amd64 Packages
gnutls_handshake() failed: Handshake failed
Err https://esm.ubuntu.com trusty-infra-updates/main amd64 Packages
gnutls_handshake() failed: Handshake failed
W: Failed to fetch https://esm.ubuntu.com/ubuntu/dists/trusty-infra-security/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed
W: Failed to fetch https://esm.ubuntu.com/ubuntu/dists/trusty-infra-updates/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: Process completed with exit code 100. …
```
=> remove Install latest git and work around permission issue

detect_cans_in_fridge_201202/CMakeLists.txt, detect_cans_in_fridge_201202/apps/pick_object/pick_object.app, detect_cans_in_fridge_201202/apps/pick_object/pick_object.l, detect_cans_in_fridge_201202/apps/pr2_fridge_demo/pr2_fridge_demo.app, detect_cans_in_fridge_201202/apps/pr2_fridge_demo/pr2_fridge_demo.l, detect_cans_in_fridge_201202/euslisp/main.l, jsk_demo_common/euslisp/pr2-action.l, rwt_teleop/apps/rwt_teleop/rwt_teleop.app
this PR is updating fridge demo to the latest version.
Now PR1040 is running this version.
this PR includes #1296 and #1299.
=> [detect_cans_in_fridge_201202] update fridge demo

jsk_maps/README.md
=> [jsk_maps] Fix improper indentations in README
